---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--fix", "--output-format=full"]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
